# Use official Python image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Copy and install dependencies first (better caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files
COPY . .

# Tell Docker that Flask runs on port 5000
EXPOSE 5000

# Command to run the app
CMD ["python", "app.py"]